#!/bin/bash

PROJECT="$HOME/final-exam/partE_automation/sample_project"
BACKUP_DIR="$HOME/final-exam/partE_automation/backups"

mkdir -p "$BACKUP_DIR"

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

tar -czf "$BACKUP_DIR/project_$TIMESTAMP.tar.gz" -C "$PROJECT" .

echo "Backup created: project_$TIMESTAMP.tar.gz"

# Keep only the newest 2 backups
ls -t "$BACKUP_DIR"/project_*.tar.gz | tail -n +3 | xargs -r rm
