#!/bin/bash

script_name=$(basename "$0")

for file in *; do

    # Skip if not a regular file
    [ -f "$file" ] || continue

    # Don't move the cleanup script itself
    [ "$file" = "$script_name" ] && continue

    # Ignore files without extensions
    [[ "$file" != *.* ]] && continue

    ext="${file##*.}"

    mkdir -p "$ext"

    mv "$file" "$ext/"
done

echo "Cleanup complete."
